CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY,
  value VARCHAR(255) NOT NULL,
  "isCompleted" BOOLEAN NOT NULL DEFAULT FALSE,
  is_editing BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);